### ISSUE TITLE
Add CODEOWNERS to auto request review on PRs

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs-actions#22]
@IEvangelist @gewarren @BillWagner

**Comment by gewarren** [comment]
This is a good idea. Do you want to add it @Youssef1313 ?

**Comment by Youssef1313** [comment]
> This is a good idea. Do you want to add it @Youssef1313 ?

I'm not sure if each folder (`docs-verifier`, `status-checker`) should have separate owners, and if so, which folder should have whom as a code owner.

**Comment by gewarren** [comment]
Yes, I think each folder should have separate owners. You can add gewarren as owner of status-checker, and you as owner of docs-verifier?

**Comment by Youssef1313** [comment]
@gewarren [code owners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners) should have write access.

@IEvangelist @BillWagner Would you be okay adding you as code-owners for docs-verifier?
